# Generated by Django 3.2.5 on 2022-01-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20220117_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timestamp',
            new_name='created_date',
        ),
    ]
