# Generated by Django 3.2.5 on 2022-01-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20220122_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post_liked',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='network.Post'),
        ),
    ]
