# Generated by Django 3.2.5 on 2022-01-23 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_post_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='post_liked',
        ),
        migrations.AddField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
