# Generated by Django 3.2.5 on 2022-01-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20220123_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='user',
            name='post_liked',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='network.Post'),
        ),
    ]
